application: car-hub
version: v5
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: api.application
  secure: always

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: always

- url: /tools/?.*
  script: tools.app
  secure: always

- url: /admin/?.*
  script: admin.app
  login: admin
  secure: always

- url: /brian/?.*
  script: brian.app
  login: admin
  secure: always

- url: /cron/?.*
  script: admin.app
  login: admin
  secure: always

- url: /news/?.*
  script: news.app
  login: required
  secure: always

- url: /settings/?.*
  script: settings.app
  login: required
  secure: always

- url: /vehicle/?.*
  script: vehicle.app
  login: required
  secure: always

- url: /api/?.*
  script: api_old.app
  login: required
  secure: always

- url: /.well-known/.*
  script: secure.app

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: latest

builtins:
- deferred: on

inbound_services:
- warmup
